### PR TITLE
Add Deepin OS as a not supported OS to the supported OS markdown in README

### PR DESCRIPTION
**Pull request by maximenoel**
# What does this PR?

Add Deepin OS as a not supported OS to the supported OS markdown in README file

### CODE REVIEW

**Comment by MalloZup** [comment]
Hi ! Thx for pr! Do you know if linux deepin provide upstream cloud images?

**Comment by maximenoel** [comment]
I know they have images for VMWare and VirtualBox. But I'm not sure we can say they are upstream cloud images. ( https://www.osboxes.org/deepin/#deepin-15-7-vmware )

**Comment by MalloZup** [comment]
@maximenoel for this project vmaware images/ or vitual-box are out of scope at moment.

At moment i plan to have KVM/libvirt support and Public Cloud later . ( vmware if upstream has interest why not but is to much later atm).

If deepin has not cloud images from upstream is not wort to add it to the list, and we need to take care on what CEPH is supporting

( i will update the table btw. We need at least the Openstack Cloud image support).

For recommended OS from CEPH see here:
http://docs.ceph.com/docs/master/start/os-recommendations/

An easy ISSUE to start with would be this one: 
https://github.com/MalloZup/ceph-open-terrarium/issues/35

With this one you might be some terraform knowledge and you can get start with modules.

Or even more easy would to fix **travis** which is currently failing. ( failing is the CI system running for GitHub projects).

Imho we can close this pr, what do you think? @maximenoel 

Imho  you can fix easy the **travis issue* and this will get you more knowledge in travis-ci, but if you feel to learn other stuff `terraform` or salt i can create some other issues. :sunflower:

**Comment by MalloZup** [comment]
this PR looks per-se good for a first contrib in Github :+1:  but i am not accepting it because the lack of official upstream cloud images. ( table updated with more intuitive doc .. :smile_cat: )

**Comment by maximenoel** [comment]
I tried to fix the issue with CI. I think I find the first issue but not yet for Fedora. I will look more closely tomorrow.

**Pull request closed without merging**
